### ISSUE TITLE
It would be amazing to have format on save for cue

### ISSUE THREAD

**Issue by vikstrous2** [cue-sh/vscode-cue#11]
It would be really awesome to be able to automatically format cue files when saving.

Info for how to implement a format on save feature: https://code.visualstudio.com/blogs/2016/11/15/formatters-best-practices
Some example code: https://github.com/prettier/prettier-vscode/blob/d4505c8cb3aa51ad255c7e19db752bc2afc6bd23/src/PrettierEditService.ts

**Comment by myitcv** [comment]
Yes, agreed! 

You could integrate `cue fmt` to work on save today if you wanted.

However, the plan is to solve this via an LSP implementation: https://github.com/cuelang/cue/issues/142

On that basis I'll close this issue because we can track things in the linked issue.

**Comment by johnallen3d** [comment]
I hope you don't mind me sharing this here @myitcv...

I have several (non-developer) teammates who are using VS Code to configure an internal service in CUE. In order to improve their user experience, I've created a VS Code extension that can be used with the `"editor.formatOnSave"` feature.

I look forward to the implementation of LSP for CUE and deprecating this extension, but for now, anyone interested in this functionality can try:

https://marketplace.visualstudio.com/items?itemName=jallen7usa.vscode-cue-fmt

**Comment by myitcv** [comment]
@johnallen3d would such a temporary measure be well-suited to https://github.com/cue-sh/vscode-cue?

**Comment by johnallen3d** [comment]
Purely from a user experience perspective (e.g. install one extension for CUE support), yes it makes sense to me @myitcv. This solution could be implemented and replaced once a suitable alternative is available via LSP.

I'd offer to draft a PR but my extension is written in TypeScript and `cue-sh/vscode-cue` appears to be written in Go. At the moment I wouldn't know where to start.
